# Default values for k3s-agent
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

image:
  repository: niusmallnan/k3s
  tag: v1.19.2-k3s1-1
  pullPolicy: IfNotPresent

runtimeClass: kata-qemu-virtiofs

k3sToken: ~
k3sURL: ~

replicaCount: 1
