# Default values for k3s-server
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

image:
  repository: niusmallnan/k3s
  tag: v1.19.2-k3s1-1
  pullPolicy: IfNotPresent

serviceCIDR: 10.45.0.0/16
clusterCIDR: 10.44.0.0/16

runtimeClass: kata-qemu-virtiofs
